name: Verify

on: 
  push:
  workflow_dispatch:

jobs:
  static_checks:
    name: Static Checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: bash formatting
        run: docker run -v "$PWD":/mnt -w /mnt mvdan/shfmt -ci -i 2 -l -d -- *.sh

  self_check:
    name: Run this Action
    runs-on: ubuntu-latest
    needs: [static_checks]
    steps:
      - uses: actions/checkout@v3

      - name: No release mode
        id: no-release
        uses: ./
        with:
          image-name: test-action
      - name: Check results no release
        run: |
          cat ${GITHUB_WORKSPACE}/metadata.json
          echo "${{ steps.no-release.outputs.docker-tags }}"
          echo "${{ steps.no-release.outputs.git-tag }}"
        shell: bash
      
      - name: Release mode
        id: release
        uses: ./
        with:
          image-name: test-action-release
          is-release: true
      - name: Check result release      
        run: |
          cat ${GITHUB_WORKSPACE}/metadata.json
          echo "${{ steps.release.outputs.docker-tags }}"
          echo "${{ steps.release.outputs.git-tag }}"
        shell: bash
